GET https://api.github.com/repos/OscarSilvaOfficial/portfolio-linkedin-service

###

GET https://api.github.com/users/OscarSilvaOfficial

###

GET https://api.github.com/users/OscarSilvaOfficial/repos

###

https://api.github.com/repos/OscarSilvaOfficial/portfolio-api/commits